from enum import Enum


class CardCountingSystem(Enum):
    HI_LO = 'HI-LO'
    HI_OPT_I = 'HI-OPT I'
    HI_OPT_II = 'HI-OPT II'
    OMEGA_II = 'OMEGA II'
    HALVES = 'HALVES'
    ZEN_COUNT = 'ZEN COUNT'
    KO = 'KO'


class HandStatus(Enum):
    IN_PLAY = 'IN PLAY'
    SETTLED = 'SETTLED'
    SHOWDOWN = 'SHOWDOWN'


class StatsCategory(Enum):
    TOTAL_ROUNDS_PLAYED = 'TOTAL ROUNDS PLAYED'
    TOTAL_HANDS_PLAYED = 'TOTAL HANDS PLAYED'
    PLAYER_HANDS_WON = 'PLAYER HANDS WON'
    PLAYER_HANDS_LOST = 'PLAYER HANDS LOST'
    PLAYER_HANDS_PUSHED = 'PLAYER HANDS PUSHED'
    PLAYER_BLACKJACKS = 'PLAYER BLACKJACKS'
    DEALER_BLACKJACKS = 'DEALER BLACKJACKS'
    PLAYER_DOUBLE_DOWNS = 'PLAYER DOUBLE DOWNS'
    PLAYER_SURRENDERS = 'PLAYER SURRENDERS'
    INSURANCE_AMOUNT_BET = 'INSURANCE AMOUNT BET'
    INSURANCE_NET_WINNINGS = 'INSURANCE NET WINNINGS'
    AMOUNT_BET = 'AMOUNT BET'
    NET_WINNINGS = 'NET WINNINGS'
    TOTAL_AMOUNT_BET = 'TOTAL AMOUNT BET'
    TOTAL_NET_WINNINGS = 'TOTAL NET WINNINGS'
